#pragma once
#include <cstdint>

enum class FieldKey : uint32_t {
	PLAYER_INVENTORY,
	PLAYER_OUTFIT_LOADOUT,
	PLAYER_WEAPON_LOADOUT,
	PLAYER_DATA,
	PROFILE_DATA,
	PLAYER_LEGACY_DATA,
	PLAYER_UNDELIVERED_MESSAGES
};